# Generated by Django 3.1.7 on 2021-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.IntegerField(choices=[(1, 'Common'), (2, 'Trainer')], default=1),
        ),
    ]
