# Generated by Django 3.1.7 on 2021-03-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='pushed_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pushed', to='accounts.user'),
            preserve_default=False,
        ),
    ]
