# Generated by Django 3.1.7 on 2021-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alert_pushed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
