# Generated by Django 3.1.7 on 2021-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitclasses', '0003_auto_20210327_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitclass',
            name='desc_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
