# Generated by Django 3.1.7 on 2021-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_article_category1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
