export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const EMAILCHECK = "EMAILCHECK";
export const GETUSERINFO ="GETUSERINFO";

export const SELFTRAINLIST = "SELFTRAINLIST";
export const SELFTRAINDETAIL = "SELFTRAINDETAIL";

export const INFO = "INFO";
export const INFODETAIL = "INFODETAIL";

export const INFOLIKE = "INFOLIKE";
export const SHOWIMAGE = 'SHOWIMAGE'
export const GETIMAGE = 'GETIMAGE'

export const VIDEOCLASS = "VIDEOCLASS";
export const VIDEOCLASSCREATE = "VIDEOCLASSCREATE";
export const VIDEOCLASSDETAIL = "VIDEOCLASSDETAIL";
export const VIDEOCLASSREGISTER = "VIDEOCLASSREGISTER";

export const ARTICLE = "ARTICLE";
export const ARTICLELIST = "ARTICLELIST";
export const ARTICLEDETAIL = "ARTICLEDETAIL";

export const COMMENT = "COMMENT";
export const COMMENTLIST = "COMMENTLIST";

export const JANDI = "JANDI";
