# Generated by Django 3.1.7 on 2021-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('yt_address', models.TextField()),
                ('category', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='%Y%m%d')),
            ],
        ),
    ]
