# Generated by Django 3.1.7 on 2021-04-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitclasses', '0004_fitclass_desc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitclass',
            name='nickname',
            field=models.CharField(default='camfit trainer', max_length=100),
        ),
    ]
